#!/bin/bash
set -eo pipefail

# coreos ami-3b14f27f
# ubuntu ami-d30be097

INIT=$(cat <<EOF
#!/bin/bash
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker ubuntu
EOF)

USER_DATA=`echo $INIT | base64`

LAUNCH_SPEC=$(cat <<EOF
{
  "KeyName": "dave",
  "ImageId": "ami-d30be097",
  "InstanceType":"c3.xlarge",
  "SecurityGroups":["ssh-standard", "minecraft"],
  "UserData": "$USER_DATA",
  "Placement": {
    "AvailabilityZone": "us-west-1a"
  },
  "EbsOptimized": true
}
EOF)

aws ec2 request-spot-instances --spot-price "0.07" \
                               --instance-count 1 \
                               --type "one-time" \
                               --launch-specification "$(tr '\n' ' ' <<< $LAUNCH_SPEC)" \
                               | jq '.'
