#!/bin/bash
set -eo pipefail

aws ec2 describe-spot-price-history \
  --instance-type c3.xlarge \
  --product-description 'Linux/UNIX' \
  | jq --compact-output '.SpotPriceHistory[] | {at: .Timestamp, price: .SpotPrice}'
