#!/bin/bash
set -eo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage : $0 addr [options]"
  exit -1
fi

function main() {
  local addr="$1"; shift
  echo "logs $addr $@"
  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$addr $@
}

main $@
