#!/bin/bash
set -eo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage : $0 addr"
  exit -1
fi

ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$1 << EOF
docker run --name minecraft -p 25565:25565 -id --restart=always \
    -v /mnt/data:/data partycloud/minecraft:ftb-infinity \
    java -Xms1024m -Xmx6144m -XX:PermSize=128m -jar server.jar nogui
EOF
